// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IJWTRSAToken is an autogenerated mock type for the IJWTRSAToken type
type IJWTRSAToken struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: userID, username
func (_m *IJWTRSAToken) GenerateToken(userID string, username string) (string, error) {
	ret := _m.Called(userID, username)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(userID, username)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParserToken provides a mock function with given fields: tokenString
func (_m *IJWTRSAToken) ParserToken(tokenString string) (string, string, error) {
	ret := _m.Called(tokenString)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(tokenString)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
