// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import repositories "github.com/dipay/repositories"

// ICountriesUseCase is an autogenerated mock type for the ICountriesUseCase type
type ICountriesUseCase struct {
	mock.Mock
}

// GetCountries provides a mock function with given fields: _a0
func (_m *ICountriesUseCase) GetCountries(_a0 context.Context) ([]repositories.CountriesPayload, error) {
	ret := _m.Called(_a0)

	var r0 []repositories.CountriesPayload
	if rf, ok := ret.Get(0).(func(context.Context) []repositories.CountriesPayload); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.CountriesPayload)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
