// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import db "github.com/dipay/internal/db"
import mock "github.com/stretchr/testify/mock"

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *Database) Client() db.Client {
	ret := _m.Called()

	var r0 db.Client
	if rf, ok := ret.Get(0).(func() db.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.Client)
		}
	}

	return r0
}

// Collection provides a mock function with given fields: _a0
func (_m *Database) Collection(_a0 string) db.Collection {
	ret := _m.Called(_a0)

	var r0 db.Collection
	if rf, ok := ret.Get(0).(func(string) db.Collection); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.Collection)
		}
	}

	return r0
}
