// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import echo "github.com/labstack/echo/v4"
import mock "github.com/stretchr/testify/mock"

// ICompanyController is an autogenerated mock type for the ICompanyController type
type ICompanyController struct {
	mock.Mock
}

// AddCompany provides a mock function with given fields: ctx
func (_m *ICompanyController) AddCompany(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCompany provides a mock function with given fields: ctx
func (_m *ICompanyController) GetCompany(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCompanyStatusActive provides a mock function with given fields: ctx, id
func (_m *ICompanyController) UpdateCompanyStatusActive(ctx echo.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
