// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import echo "github.com/labstack/echo/v4"
import mock "github.com/stretchr/testify/mock"

// ICountriesController is an autogenerated mock type for the ICountriesController type
type ICountriesController struct {
	mock.Mock
}

// GetDataCountries provides a mock function with given fields: ctx
func (_m *ICountriesController) GetDataCountries(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
