// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import repositories "github.com/dipay/repositories"

// ICountriesRepository is an autogenerated mock type for the ICountriesRepository type
type ICountriesRepository struct {
	mock.Mock
}

// GetCountries provides a mock function with given fields: ctx
func (_m *ICountriesRepository) GetCountries(ctx context.Context) ([]repositories.CountriesPayload, error) {
	ret := _m.Called(ctx)

	var r0 []repositories.CountriesPayload
	if rf, ok := ret.Get(0).(func(context.Context) []repositories.CountriesPayload); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.CountriesPayload)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
