// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// IUserAdminRepository is an autogenerated mock type for the IUserAdminRepository type
type IUserAdminRepository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, filter, result
func (_m *IUserAdminRepository) Fetch(ctx context.Context, filter interface{}, result interface{}) error {
	ret := _m.Called(ctx, filter, result)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, interface{}) error); ok {
		r0 = rf(ctx, filter, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
